name: Build Bisq

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]
            java: [ '11', '11.0.3', '15', '15.0.5']
    name: Test Java ${{ matrix.Java }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK
      uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
